# Generated by Django 3.1 on 2020-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='confidence',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='reward',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='risk',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
