# Generated by Django 3.1 on 2020-09-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strat', '0004_auto_20200829_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='position_size',
        ),
    ]
